### ISSUE TITLE
New release - 0.11.0

### ISSUE THREAD

**Issue by sitaktif** [pypi/stdlib-list#122]
Last release ([v0.10.0](https://github.com/pypi/stdlib-list/releases/tag/v0.10.0)) was from 18th Nov 2023.

At the time of writing, 19 commits have been contributed since ([link](https://github.com/pypi/stdlib-list/compare/v0.10.0...main)).

It would be great to create a new release that contains these changes.

Motivation, for context: stdlib-lists are used in [Bazel's python rules](https://github.com/bazelbuild/rules_python/blob/084b877c98b580839ceab2b071b02fc6768f3de6/gazelle/deps.bzl#L27-L58) and are currently referring to a commit specific "raw" Github link (referring to individual git tree source files), which is not ideal. I would like to make a contribution to refer to an official release of the project instead.

**Comment by woodruffw** [comment]
Hey @sitaktif, thanks for filing this.

All of the commits since then have been routine workflow updates, plus a small documentation PR and a linting fix. Are these blockers for using `v0.10.0`? That release should contain exactly the same code as a hypothetical `v0.11.0` would 🙂 

(If a new release would still be easier, then I don't mind creating it. But it'll likely be `v0.10.1` because no semver additions have occurred.)

**Comment by sitaktif** [comment]
Thanks @woodruffw, I should have looked a bit more closely; if all these changes are just minor background fixes that don't affect the code, I see no reason to create a new release 🙂

Appreciate you taking the time to answer!

**Comment by woodruffw** [comment]
No problem! Please do let us know if you run into any issues with the release, and we'll be happy to try and address them.
